"""Training utilities for UAV navigation experiments."""

from r1_uav_nav.training.colosseum_td3 import (
    DEFAULT_CONFIG_PATH,
    EVALUATION_POLICY_KINDS,
    ColosseumTD3Config,
    ColosseumTD3RunResult,
    EvaluationEpisodeMetrics,
    TrainingEpisodeMetrics,
    apply_evaluation_overrides,
    apply_training_overrides,
    evaluate_colosseum_td3,
    load_colosseum_td3_config,
    resolve_device,
    train_colosseum_td3,
)
from r1_uav_nav.training.long_run_state import (
    CheckpointManifest,
    LongRunRunState,
    ResumeMode,
    ResumePlan,
    SafeCheckpoint,
    discover_latest_safe_checkpoint,
    validate_resume_request,
)
from r1_uav_nav.training.long_run_training import (
    DEFAULT_LONG_RUN_CONFIG_PATH,
    LongRunTD3Config,
    LongRunTrainingResult,
    SafeCheckpointCallback,
    load_long_run_td3_config,
    run_fake_td3_smoke,
    validate_long_run_configuration,
)

__all__ = [
    "ColosseumTD3Config",
    "ColosseumTD3RunResult",
    "CheckpointManifest",
    "DEFAULT_CONFIG_PATH",
    "DEFAULT_LONG_RUN_CONFIG_PATH",
    "EVALUATION_POLICY_KINDS",
    "EvaluationEpisodeMetrics",
    "LongRunRunState",
    "LongRunTD3Config",
    "LongRunTrainingResult",
    "ResumeMode",
    "ResumePlan",
    "SafeCheckpoint",
    "SafeCheckpointCallback",
    "TrainingEpisodeMetrics",
    "apply_evaluation_overrides",
    "apply_training_overrides",
    "evaluate_colosseum_td3",
    "discover_latest_safe_checkpoint",
    "load_colosseum_td3_config",
    "load_long_run_td3_config",
    "resolve_device",
    "run_fake_td3_smoke",
    "train_colosseum_td3",
    "validate_long_run_configuration",
    "validate_resume_request",
]
