"""Simulator integration helpers."""

from r1_uav_nav.sim.colosseum_client import (
    CleanupResult,
    CleanupState,
    ColosseumClientError,
    ColosseumClientImportError,
    cleanup_after_control,
    confirm_connection,
    create_multirotor_client,
    get_multirotor_state_summary,
    import_colosseum_client_module,
    perform_basic_control_check,
    read_multirotor_state,
)
from r1_uav_nav.sim.waypoint_navigation import (
    NavigationConfig,
    Position3D,
    RouteExecutionResult,
    RouteParameters,
    WaypointOffset,
    WaypointProgress,
    calculate_position_error,
    execute_route,
    execute_route_suite,
    expand_route_selection,
    generate_figure_eight,
    generate_horizontal_square,
    generate_vertical_square,
    read_collision_status,
    resolve_waypoints,
    validate_navigation_config,
    validate_route_clearance,
)

__all__ = [
    "CleanupResult",
    "CleanupState",
    "ColosseumClientError",
    "ColosseumClientImportError",
    "NavigationConfig",
    "Position3D",
    "RouteExecutionResult",
    "RouteParameters",
    "WaypointOffset",
    "WaypointProgress",
    "calculate_position_error",
    "cleanup_after_control",
    "confirm_connection",
    "create_multirotor_client",
    "execute_route",
    "execute_route_suite",
    "expand_route_selection",
    "generate_figure_eight",
    "generate_horizontal_square",
    "generate_vertical_square",
    "get_multirotor_state_summary",
    "import_colosseum_client_module",
    "perform_basic_control_check",
    "read_collision_status",
    "read_multirotor_state",
    "resolve_waypoints",
    "validate_navigation_config",
    "validate_route_clearance",
]
